### ISSUE TITLE
"Hello, World!"

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus.io#12]
After setting up a development environment https://github.com/teamforus/forus/issues/11 create a "Hello, World!" that implements:

See https://github.com/teamforus/forus/tree/master/docs#architecture for an overview

Repo | Description | Assignee
-------|-------|----
**me | Identity | 
**forus.io	|	Core shop | 
**api.forus.io		|	API | 
**services.forus.io		|	Services | 
**forus.io-nodejs	|	NodeJS | 
**forus.io-mongodb		|	MongoDB | 
forus.io-ipfs	|	JSON-LD | 
forus.io-ethereum	|	Contracts | 

**Priority

- [ ] choose what the hello world will do
- [ ] set up containers
- [ ] deploy to aws

**Comment by jamalv** [comment]
We should probably keep it as simple as possible, something like a simple read-write from the front end (forus.io / me app) to mongodb using nodejs trough the api and go from there.

**Comment by maxvisser** [comment]
I can deploy a IPFS container to AWS that does not connect to the bootnodes of IPFS.io making it a private node. https://github.com/teamforus/forus.io/issues/32 Let's start by pinning a file to ipfs via rabbitmq. How do we want to set this up.

my proposal is to use the api written by Jasper at common ground as a hello world example doing the api calls via rabbitMQ.

**Comment by jamalv** [comment]
This should also connect to front-ends like the native apps and a simple website.

**Comment by maxvisser** [comment]
superseded by https://github.com/teamforus/forus.io/issues/53
