### ISSUE TITLE
Oracle design/functionality/technology

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus.io#14]
The [oracle](https://blockchainhub.net/blockchain-oracles/) is an API for all "traditional" functionality. See the [architecture](https://github.com/teamforus/forus/issues/13) for more context.

Functionality examples: 
* bunq API
* KVK API
* DB Connections
* DigiD
* Emails
* Managing user accounts for users without a me app

We should decide what technology to use for it. Since we already implemented a lot of this functionality in the current PHP system, is it a good idea to also implement the oracle in PHP as well?

**Comment by maxvisser** [comment]
I think the services should be able to accept asynchronous api requests. Using PHP for BUNQ is ok for Zuidhorn, we should maybe try to use the python SDK for other implementations

**Comment by jamalv** [comment]
yea, we basically decided on using php for this, this issue is superseded by the new architecture.
