### ISSUE TITLE
Flowchart [v0.2]. Current version: v0.2

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus.io#15]

**Comment by maxvisser** [comment]
![flowchart](https://user-images.githubusercontent.com/10818702/38618621-803b0f6e-3d9a-11e8-843d-376c208bb2ab.png)

**Comment by maxvisser** [comment]
@danrminds can you post your latest version as a .png here? when you export from draw.io can you include a copy of your drawing ?

![copy](https://user-images.githubusercontent.com/10818702/38663783-1999129e-3e38-11e8-84ae-07b821bb0395.png)

**Comment by danrminds** [comment]
did not change yet. So the upper is the last version still. I worked more on the "registration of business" and me app flowchart. 
Will continue with this one today.

**Comment by danrminds** [comment]
![general flowchart v 0 1 2](https://user-images.githubusercontent.com/33207036/38680730-4b5fac1e-3e67-11e8-9df6-9b330b12a12e.png)

Updated flowchart. v 0.1.2

**Comment by danrminds** [comment]
![general flowchart v0 1 3](https://user-images.githubusercontent.com/33207036/38698010-e6dd03d6-3e93-11e8-9648-c30128dfb2c6.png)

Updated flowchart. v0.1.3

**Comment by danrminds** [comment]
[Big diagram.pdf](https://github.com/teamforus/forus.io/files/1948391/Big.diagram.pdf)
