### ISSUE TITLE
Sponsor v2 wireframes

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus.io#18]
Based on: https://github.com/teamforus/forus/issues/2

## **Wireframe requirement list**
create budget - out of scope
select validators - out of scope
set validation criteria - out of scope

- [x] edit funding
  - [x] select funding amount per request
  - [x] Select total funding amount 
- [x] set criteria
- [x] shopkeeper validation
  - [x] list of providers to fund
  - [x] list of products to fund
  - [x] allocation of funds
- [x] Financial dashboard
  - [x] overview over shops
  - [x] Debts
  - [x] Fund allocation
- [ ] Secondary sponsor
  - [ ] add fund to existing fund 
  - [ ] allocate to different category

based on flowchart #15

**Comment by maxvisser** [comment]
![decision_tree_wireframe](https://user-images.githubusercontent.com/10818702/38503943-b5cc6da4-3c13-11e8-8bdf-13f105680cb4.png)

Decision tree wireframe based on Microsoft Flows. A sponsor can set criteria based on conditions and action. A action can be a 'Success', 'Deny' or another condition.

https://drive.google.com/open?id=1TcdIxO912q6FQMRVwAgcd6_mRjoXDRes

**Comment by maxvisser** [comment]
![sponsor_wireframe 1](https://user-images.githubusercontent.com/10818702/38677324-40e016b0-3e5e-11e8-9964-4e4a59f4a4a3.png)

wireframe sponsor; login with me app, go to sponsor page, buy plan, create fund, set criteria

Github pricing plan as placeholder.

**Comment by maxvisser** [comment]
discussed with @danrminds that letting sponsors set up criteria themselves is alot of work and possible not doable before august. (last screen of wireframe)

**Comment by danrminds** [comment]
![01 sponsor dashboard](https://user-images.githubusercontent.com/33207036/38773036-2006a138-4044-11e8-9bb7-35a80dd7a46e.png)

Sponsor flowchart. v.0.0.2

**Comment by maxvisser** [comment]
![sponsor_main](https://user-images.githubusercontent.com/10818702/38811922-2ac20020-418b-11e8-9d7c-fc1b1c1ce19a.png)

added view funds, shopkeeper validation, special offer validation, financial dashboard

**Comment by maxvisser** [comment]
![38677483-b09d7b96-3e5e-11e8-9330-6c5af8a0532e 1](https://user-images.githubusercontent.com/10818702/38812329-4f85b7b6-418c-11e8-85e9-9cf91d691b5e.png)
Application proces sponsor

need to add the real pricing plan of Forus and the 'application finished' page with information.

**Comment by jamalv** [comment]
@maxvisser Nice! Would like to take one more thing into consideration: funding on a per category/special-offer basis. e.g. adding extra funding to the "sport" category. Or allocating funding to the "batavus star 20 inch" special offer. This is not only for Zuidhorn but also for other sponsors like sport fund who would like to lift along with the municipality. For the requester this would mean that they would have to see their available funding on a per-category / per-special-offer basis.

**Comment by maxvisser** [comment]
I will start wireframing the 'secondary sponsor' soon™
@danrminds do you agree with Jamalv?

The more easy approach would be to main sponsor allocate resources.

**Comment by jamalv** [comment]
We've made the decision to move on to the design stage, and iterate further there.
