### ISSUE TITLE
Validator v2 wireframes 

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus.io#19]
based on https://github.com/teamforus/implementation/issues/12 and https://github.com/teamforus/forus/issues/3

- [x] manual validation @maxvisser
- [ ] validator types
- [ ] automated validation
- [ ] register organisation
- [x] login to validator dashboard
- [x] validate citizen information

was not in flowchart
- [x] History validations

**Comment by maxvisser** [comment]
added in flowchart requirements from @danrminds

**Comment by maxvisser** [comment]
![validator_dashboard](https://user-images.githubusercontent.com/10818702/39049391-98721664-44a1-11e8-82cb-64effd6d3e78.png)

**Comment by maxvisser** [comment]
I find it hard to wireframe task 2, 3 and 4. I think 2 and 4 are for the Me app and 3 is a background task.

**Comment by maxvisser** [comment]
![39049391-98721664-44a1-11e8-82cb-64effd6d3e78 1 1](https://user-images.githubusercontent.com/10818702/39116833-b0652bd0-46e5-11e8-981a-aef5c260214a.png)

**Comment by jamalv** [comment]
We've made the decision to move on to the design stage, and iterate further there.
