### ISSUE TITLE
Provider v2 wireframes

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus.io#20]
Based on https://github.com/teamforus/forus/issues/5
- [ ] registration
- [ ] business registration
- [ ] share business details kvk number
 -[X] login to dashboard
- [ ] see list of available funds per product
  - [x] select products that can be provided
    - [x] select quantity or availability 
  - [x] select the upper limit price
  - [x] check price limit compared to sponsor limit

**Comment by maxvisser** [comment]
Registration/business registration, sharing kvk etc is a wireframe for https://github.com/teamforus/me right?

**Comment by maxvisser** [comment]
![provider_wirefrime](https://user-images.githubusercontent.com/10818702/38737899-003f4b16-3f31-11e8-8276-5874b7c09819.png)

**Comment by maxvisser** [comment]
v0.2
![38739073-28a2812e-3f34-11e8-830c-f27c34e16dbf 1](https://user-images.githubusercontent.com/10818702/39187539-e2f393c8-47cd-11e8-98dd-41fb946526ee.png)

**Comment by jamalv** [comment]
We've made the decision to move on to the design stage, and iterate further there.
