### ISSUE TITLE
Transactions: which happen on blockchain MVP

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus.io#25]
![untitled diagram 1](https://user-images.githubusercontent.com/10818702/39043697-60d9e7c6-448e-11e8-8ac1-16601bffa39d.png)

We have two options for the MVP. Only the the exchange of value between sponsor and the provider happen on blockchain or all transaction happen on blockchain.

Dan, Jamal and me are liking the first option more; We see multiple pro's for this option for the MVP. I can do a summarization:

# first option
only the exchange of value between sponsor and provider
## pros
- token do not need any restriction, it is a truely issued back token and therefore a freely exchangable currency
- Migrating to mainnet is alot closer; privacy issues are of no concern. Currently the eth dev community is not working on any of our privacy issues (only on scalability and security). Timeframe to mainnet is maybe 1 a 2 years 
- More traditional back-end means more stability
## cons
- requesters are not self-souvereign / own their own tokens

# second option
all transaction happen on blockchain
## pros
- requester owns tokens and is more self-sovereign
## cons
- this option can't migrate to mainnet until privacy issues are solved and therefore we are stuck on privatechain for an estimate of 5 years

**Comment by jamalv** [comment]
We discussed on friday that even though the first picture looks more decentralized, the transactions between the requester and sponsor will have to be on a private chain until we implement a good way to guarantee the requesters privacy, which can take a while. The transactions between sponsor and provider are much less sensitive and involve fewer parties. Therefore it will probably sooner be feasible to set up the transactions between them using main net. Therefore we have agreed that image 1 is the best first step to take.
