### ISSUE TITLE
Draw.io export pushing to repo.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus.io#27]
Let's push all wireframes and flowcharts to the docs folder of this repo. 

- [x] sponsor v0.1
- [x] validator v0.1
- [x] requester v0.1
- [x] provider v0.1

How do you guys feel about seperating all the screens from all the wireframes? because there are alot of the same screens in all the wireframes and its easier to finish seperate frames than all in one go.

- [x] big flowchart v0.1

**Comment by jamalv** [comment]
Agree with this issue 👍 

I think it would be nice to have a big overview to see how everything relates and where we can work on the wireframes, indeed it would be good to put it in the docs folder so we have it under version control.
