### ISSUE TITLE
Research usage of IPFS

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus.io#32]
Research on the usage of IPFS and closing ports / environment

- [x] set up IPFS node in docker container
- [x] test out private network experimental feature
- [x] try out interplanetary TestBed

**Comment by maxvisser** [comment]
experimental feature:
https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks

**Comment by maxvisser** [comment]
https://github.com/ipfsconsortium IPFS consortium: pinning eachothers content via smart contracts

**Comment by maxvisser** [comment]
https://github.com/ipfs/iptb/issues/50 this is also something we are looking for. simulating the real world with a IPFS testnet.

**Comment by maxvisser** [comment]
Decided together with Jasper and Jamal that a docker container consisting one IPFS node is enough as a result of this research. We should start connecting IPFS via rabbitmq to a php script and pin a file.
