### ISSUE TITLE
Add localization: all messages displayed to user ('$this->message') should be added to a language file.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus.io#38]
If we start using a language file from the start it would be easier in a later stage to translate the messages to a different language and reuse specific words like 'Error'.

A benefit from implementing localization is that all spellings errors could be fixed easier; @linda-90 and @GerbenBosschieter have some knowledge about basic scripting in HTML/CSS and could help keeping the language file up-to-date. 

## Resources
laravel docs: https://laravel.com/docs/5.6/localization

example in code base:
https://github.com/teamforus/forus.io/blob/c8d696f58423f923aefdafe8e036fdf0465e7a87/backend-php/app/Rules/IdentityOldPinCode.php#L45

**Comment by danrminds** [comment]
Localization for languages implemented during refactoring.
